- io-pay-portal-fe/src/features/payment/components/InputCardForm/InputCardForm.tsx
- io-pay-portal-fe/src/routes/InputCardPage.tsx
- io-pay-portal-fe/src/routes/PaymentCheckPage.tsx
- io-pay-portal-fe/src/utils/api/apiService.ts
- io-pay-portal-fe/src/utils/api/helper.ts
- io-pay-portal-fe/src/utils/sessionData/WalletSession.ts
- io-pay-portal-fe/src/utils/storage/sessionStorage.ts
Binding BE inputcard for sessionToken and Waller
> Add binding session wallet

- io-pay-portal-fe/src/App.tsx
- io-pay-portal-fe/src/routes/KOPage.tsx
- io-pay-portal-fe/src/translations/it/translations.ts
> Add ko page

- src/components/commons/Header.tsx
- src/features/payment/models/paymentModel.ts
- src/routes/PaymentSummaryPage.tsx
- src/translations/it/translations.ts
- src/utils/api/apiService.ts
- src/utils/api/client.ts
- src/utils/api/helper.ts
- src/utils/api/response.ts
This PR fix the Paymodel that hasn't optional data like the type exported by client
- Set undefined when optional
-
This PR fix the Paymodel that hasn't optional data like the type exported by client
> [#IOPAY-528] Fix paymodel with optional data.

- package.json
- add api spec for transactions API with : 
- https://raw.githubusercontent.com/pagopa/pagopa-functions-checkout/v1.1.5/api-spec/api-fn-for-checkout.yml
> Fix api spec for transactions API

- src/App.tsx
- src/index.html
- src/onetrust.js
- src/routes/PaymentResponsePage.tsx
- src/utils/api/helper.ts
- src/utils/api/response.ts
- src/utils/config/mixpanelDefs.ts
- src/utils/config/mixpanelHelperInit.ts
- src/utils/iframe/iframe.ts
- src/utils/transactions/transactionHelper.ts
The goal of this PR is to integrate OneTrust banner cookies
- added specific js to download script from OT cdn
- added eventlistern useful to intercept changing consent
- optim. of mixpanel stuffs
We need to inform user about cookies
> [#IOPAY-454] onetrust

- .devops/pagopa-code-review-pipelines.yml
* Add `develop` branch to code review pipeline
> Code review pipeline on develop

- .devops/pagopa-deploy-pipelines.yml
- src/utils/api/client.ts
- Update pm host for DEV env
- payment-transaction host #36
> Update pm host for DEV env and payment-transaction host

- src/utils/config/mixpanelHelperInit.ts
- Fix check to disable mixpanel in DEV env, the correct value for `CHECKOUT_ENV` is `DEV`
> Fix check to disable mixpanel in DEV env

- src/utils/iframe/iframe.ts
-  Remove `onBrowserUnload` in  3ds flow;
The goal of this PR is to remove onBrowserUnload when redirecting to ACS (form --> submit) according to [3ds2 flow](https://pagopa.atlassian.net/wiki/spaces/I/pages/92537795/pagoPA+-+checkout+Design+Review#vpos);
> [IOPAY-532] Remove onBrowserUnload for 3ds

- package.json
- response.html
-  add response.html for redirect to use in rollout
> Add response.html for rollout Checkout 2.0

- .devops/azure-templates/setup-env.yml
- .devops/pagopa-deploy-pipelines.yml
> Fix dev and uat pipelines

- src/components/PrivacyPolicy/PrivacyInfo.tsx
> Fix merge for privacypolicy

- src/translations/it/translations.ts
> [IOPAY-602] Update translations it for donation

- src/components/PrivacyPolicy/PrivacyInfo.tsx
- src/translations/it/translations.ts
> Merge IOPAY-602 main

- src/components/modals/ErrorModal.tsx
- src/routes/PaymentNoticePage.tsx
- src/routes/PaymentSummaryPage.tsx
> Merge IOPAY-603 main 

- src/translations/it/translations.ts
> [IOPAY-610] Update translations.ts

- src/components/commons/Footer.tsx
- src/translations/lang.ts
Drop unused languages.
Optimize the menu display, showing it only in case of multiple lang configured.
- drop lang from dictionary
- condition on menu display
> [HOTFIX] Drop unused lang

- privacypolicy/it.html
This PR updates privacy policy's text according to the Legal's desiderata.
- privacy policy it
> [#IOPAY-601] Update privacy text

- src/translations/it/translations.ts
> [IOPAY-630] Update translations.ts

- src/translations/it/translations.ts
> [IOPAY-633] Update translations.ts

- src/__integration_tests__/checkout.integration.test.ts
- src/__integration_tests__/utils/helpers.js
> Merge develop to main

- src/components/commons/Header.tsx
- src/components/modals/CustomDrawer.tsx
- src/redux/slices/checkData.ts
- src/routes/PaymentNoticePage.tsx
- src/utils/api/apiService.ts
- src/utils/transformers/paymentTransformers.ts
This PR fixes the grey background on paper in Check page drawer
Fix background on drawer paper
> Fix grey background on paper

- src/components/PageContent/CheckoutLoader.tsx
- src/routes/PaymentNoticePage.tsx
This FIX enable error messages after a payment started with a qr scan
> [#IOPAY-644]  fix error after qr

- src/components/PageContent/CheckoutLoader.tsx
This FIX solve an issue with the "loader" displayed on several pages
> FIX top value

- .devops/pagopa-deploy-pipelines.yml
> Deploy in prod only with manual approval

- package.json
- yarn.lock
This PR update MUI-italia to the version 0.6.10
- update mui-italia to 0.6.10
- update packages with dep as mui-material and style cause the "new verions" of mui-italia doesn't have a strictly dependency as the first ones
Update the look & feel
> [#CHK30] Update MUI-italia to 0.6.10

- src/index.html
The goal is to to improve performance using `preconnect` to external resources
> [#CHK-348] Added preconnect tips

- src/components/Header/DrawerDetail.tsx
> Fix typography color

- src/components/Header/DrawerDetail.tsx
This PR removes border bottom from header's drawer title.
> Delete border bottom header's drawer

- src/utils/api/helper.ts
This PR fixes a missing error handling on response != 200 from checkout donations api
Added response check for response != 200
> Fix donations resp != 200

- src/routes/PaymentSummaryPage.tsx
- src/utils/form/formatters.tsx
> fix codice avviso separato

- src/routes/PaymentCheckPage.tsx
- src/routes/PaymentChoicePage.tsx
This PR adds amount query string on trasparenza costi link
> add query string trasparenza costi

- src/translations/it/translations.ts
> [#CHK-614] Edit causale

- .devops/pagopa-deploy-pipelines.yml
- update PM host for dev env --> https://api.dev.platform.pagopa.it/payment-manager
- update PM host for uat env --> https://api.uat.platform.pagopa.it/payment-manager
The goal of this PR is to call the `PM` API through the `pagoPA API Management`, only for DEV and UAT environments.
> PM through apim for dev and uat 

- .devops/pagopa-deploy-pipelines.yml
- update endpoint for PM api
The goal of the PR is to update PM api endpoint to route traffic to the apim pagoPA.
> feat: PM api via apim pagoPA

- src/translations/it/translations.ts
Copy update
This PR adds a new sentence in the main page of the donation service, clarifying the initiative will end on Dec 23.
> [CHK-861] Copy update

- .devops/pagopa-code-review-pipelines.yml
- src/__integration_tests__/checkout.integration.test.ts
- src/__integration_tests__/utils/helpers.js
- src/components/FormButtons/FormButtons.tsx
- src/features/payment/components/PaymentEmailForm/PaymentEmailForm.tsx
- src/features/payment/components/PaymentNoticeForm/PaymentNoticeForm.tsx
- src/routes/PaymentCheckPage.tsx
- src/routes/PaymentSummaryPage.tsx
Added two optional parameters to the FormButtons component to handle ids in the html buttons.
Modified the tests by adding the error cases and replacing the full xpaths in the tests for button positions with selectors using the ids .
To optimize the handling of graphics component retrieval during test execution, ids were assigned to the html buttons. In addition, tests were added for error cases received by the node : 
-  PPT_STAZIONE_INT_PA_SCONOSCIUTA
-  PPT_DOMINIO_SCONOSCIUTO
The tests were carried out by running the code review pipeline in when it is in charge of running all the modified tests.
> CHK-926 removed full xpath handling new error test

- .devops/pagopa-deploy-pipelines.yml
- src/__integration_tests__/checkout.integration.test.ts
Added e2e tests in the deploy pipelines for UAT and DEV.
It was managed in the deployment pipeline the execution of the e2e tests defined in the pagopa-checkout-test project in the e2e-tests folder by replacing at run time the placeholder related to the URL on which to run the tests in the .env file of the checkout-test project.
The tests were performed by running the deploy pipelines
Depends on pagopa/pagopa-checkout-tests#31
> CHK-903  e2e-tests into deploy pipeline

- src/components/PrivacyPolicy/PrivacyInfo.tsx
- src/translations/it/translations.ts
This PR updates disclaimer legal IT text. 
Update disclaimer legal
- [x, ] New feature (non-breaking change which adds functionality)
> [CHK-700] Update disclaimer legal

- .devops/pagopa-code-review-pipelines.yml
- .env.development
- src/__integration_tests__/checkout.integration.test.ts
- src/__integration_tests__/utils/helpers.js
Added new test methods for new payment flow with ecommerce.
Integration tests have been updated to handle the new ecommerce flow.
In particular, failure scenarios for activation and authorization requests
Testing was carried out by running the integration test stage of the code review pipeline.
> CHK-975-e2e-tests-for-new-ecommerce-flow

- src/utils/api/helper.ts
Add authBearer in getTransaction and postAuthReqeust
The invocation of the rest api mentioned enriched with reqeust parameters
new ecommerce api dedicated invocation implemented
Tests were performed locally
> [CHK-1096] use bearer in auth request and get transaction

- src/utils/__tests__/TransactionResultUtil.test.ts
- src/utils/transactions/TransactionResultUtil.ts
> Fix new authorization status test

- src/utils/api/response.ts
- src/utils/transactions/transactionHelper.ts
Add bearerAuth to getTransaction in page esito
Get bearerAuth from sessionStorage and pass it to the getTransactionCalling
Security protection for getTransaction
> add bearerAuth to getTransaction

- src/utils/api/response.ts
Update pipe to get transaction id and bearer auth to pass to getTransaction
update the transaciton id and bearer auth pipe in response page
> Fix lint response

- .devops/pagopa-code-review-pipelines.yml
- jest-puppeteer.config.js
- src/__integration_tests__/checkout.integration.test.ts
- src/__integration_tests__/utils/helpers.js
- src/components/FormButtons/ErrorButtons.tsx
- src/components/modals/CancelPayment.tsx
- src/components/modals/ErrorModal.tsx
- src/features/payment/components/PaymentPspDrawer/PaymentPspDrawer.tsx
- src/routes/InputCardPage.tsx
- src/routes/PaymentCheckPage.tsx
- src/routes/PaymentResponsePage.tsx
- src/utils/api/helper.ts
- src/utils/storage/sessionStorage.ts
Update dto from infra. Add integration test to gec integrated branch of checkout-fe
Edit all dto about calculate/fee api caused by infra refactorin
Add integration test
> [CHK-1239] refactoring dto and integration test

- .devops/pagopa-deploy-pipelines.yml
- .env.development
cdn logos address contains final slash char not needed
> [Chk 1276] cdn loghi

- src/utils/__tests__/TransactionResultUtil.test.ts
- src/utils/transactions/TransactionResultUtil.ts
Changed single status NOTIFIED with new NOTIFIED_OK and NOTIFIED_KO status.
> fix: NOTIFIED to NOTIFIED_OK and NOTIFIED_KO

- src/utils/transactions/TransactionResultUtil.ts
Fix final status enumeration with new transaction statusCode
> changed final status enum

- src/__integration_tests__/utils/helpers.js
- src/routes/PaymentCheckPage.tsx
- src/routes/PaymentChoicePage.tsx
- src/utils/api/client.ts
- src/utils/api/helper.ts
Added handling of the api DELETE transaction/{id} to cancel a transaction.
Also added parametric handling on the close button of the PaymentCheckPage error modal. If there is an error between 400 and 500 excluded on the DELETE transaction, a navigate to the home page will be performed.
Added a retry on the POST calculate fees in case of an error.
Added handling of cancellation of a transaction.
The tests were performed locally.
> CHK-1261-cancel-payment-call

- src/utils/api/helper.ts
Depends on: 
-  [checkout BE mock](https://github.com/pagopa/pagopa-checkout-be-mock/pull/38)
- [INFRA](https://github.com/pagopa/pagopa-infra/pull/830) 
Modified method to retrieve all payment methods according to specification change
Those modifications are needed in order to be compliant to payment-methods api refactoring
Local test using checkout be mock
> fix: modification according to new methods api

- src/utils/api/helper.ts
Update max occurences value for afm calculateFees
Update max occurences in calculateFees when it is invoked from client
AFM return list was cut since null value for maxOccurences has the meaning of 10 as max size
> Update max occurences for calculate fees

- package.json
- src/features/payment/models/paymentModel.ts
- src/utils/api/helper.ts
Depends on https://github.com/pagopa/pagopa-infra/pull/875
Added in the request to activate a payment the reference to the idCart if present in the session storage.
The modification has been carried out in order to allow the valorization of the field paymentNote of the activateV2 carried out from the transaction service.
The tests were performed locally.
> CHK-1401-added-idCart-activation

- src/components/commons/Header.tsx
- src/utils/api/helper.ts
CR pipeline: https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=92274&view=results
Checkout BE mock related PR: https://github.com/pagopa/pagopa-checkout-be-mock/pull/42
1. Handle multiple carts payment notices into transaction POST transaction request: payment notice list is build taken information from session storage saved cart information
2. Fix resume page total amount: total amount is calculated from cart first, if present with fallback to single payment amount. This fix is required since also in carts flow single payment informations are calculated taking into account the first cart item
Those fixes are required to handle cart with multiple payment notices correctly.
Test have been performed locally using checkout be mock
Information box with multiple payment …
> fix: handle carts multiple payment notices

- src/components/commons/Header.tsx
- Fix notice number construction from rptId `slice(11)`
> [CHK-1475] fix drawer noticeNumber 

- package.json
Changed reference branch name for ecommerce openapi
The change was made to use the main branch in the package.json for openapi ecommerce
> Fix reference branch ecommerce

- package.json
- src/utils/__tests__/TransactionResultUtil.test.ts
- src/utils/transactions/TransactionResultUtil.ts
Managed the new sendPaymentResult outcome **NOT_RECIEVED**. 
The taking charge page is conditioned by the information received from the GET transaction:
> stato CLOSED and sendPaymentResultOutcome === NOT_RECIEVED 
The change was made to strengthen the check for displaying the sendPaymentResult.
> feat:handled NOT_RECIEVED state for sendPaymentResult

- src/components/commons/Header.tsx
👉🏻 Space between import and cart icon added. 
After the change 👀
The change was made to add a space between the amount and the cart icon 🚀
> fix(space): space between amount and cart icon added

- .devops/pagopa-deploy-pipelines.yml
> feat: update release branch

- .devops/pagopa-deploy-pipelines.yml
> fix: update release branch

- src/components/TextFormField/PspFieldContainer.tsx
* fix(payment-check-page): fix psp selection drawer image sizing
This PR fixes a visual bug where PSP logos would be displayed stretched and/or squished in some cases.
> [CHK-1760] fix(payment-check-page): fix psp selection drawer image sizing

- dev-server.js
- src/translations/it/translations.ts
- src/utils/errors/errorsModel.ts
- Add new error modal specific for `PAA_PAGAMENTO_SCONOSCIUTO` error on verify payment notice
- Improve UX
- Locally with `dev-server.js` as backend
> [CHK-991] feat: update PAA_PAGAMENTO_SCONOSCIUTO error modal on verify

- package.json
- src/features/payment/components/IframeCardForm/IframeCardField.tsx
- src/features/payment/components/IframeCardForm/IframeCardForm.tsx
- src/utils/api/helper.ts
- src/utils/config/mixpanelDefs.ts
- yarn.lock
A refactoring of "npg fields call" using the autogen client & iterfaces.
- Refact code
- Use of autogen interface
> [#CHK-1789] Refinement: autogenerate client sessions

- package.json
- src/utils/api/helper.ts
Added bearerAuth and x-transaction-id-from-client header into call for retrieve card data.
The change was made to securitize the api for card data retrieval.
> feat(jwt): CHK-1860 jwt check into retrieve card data method

- package.json
- src/routes/PaymentCheckPage.tsx
- src/utils/api/helper.ts
The aim of this task/PR is to drop cardData from the auth-request post. The new arch works only with the sessionId provided in the previous call (via NPG)
- Drop cardData 
- Added sessionId to the post
- Drop unuseful imports
The aim of this task/PR is to drop cardData from the auth-request post. The new arch works only with the sessionId provided in the previous call (via NPG)
> [#CHK-1866] new detail to post for auth-request

- src/features/payment/components/IframeCardForm/IframeCardForm.tsx
- src/features/payment/components/IframeCardForm/types.ts
- disabling form data confirm button during a submit
- reenabling the button if there is a error during the submit
- renaming of state variables
- using a plain object for the form status
- removed dummy state
- removed form validation from state
Disables the submit button of the `inserisci-carta` page during the handling of the submit, so to avoid multiple clicks from the user. The button is re-enabled in case of errors, giving the user the possibility of retrying the form submit.
> [CHK-1879] Card Form button status and refactoring

- src/utils/api/helper.ts
POST transactions/{id}/auth-requests: threeDSData property removed on details
threeDSData should be unuseful now with the new NPG integration
Inspecting the request locally
before:
now:
> [CHK-1890] unuseful threeDSData property removed

- src/features/payment/components/IframeCardForm/IframeCardForm.tsx
- src/routes/GdiCheckPage.tsx
- src/utils/api/client.ts
- src/utils/api/helper.ts
We've to catch errors and exceptions on the "Iframes card page".
- added the error modal
- wrote the error handlers for the sessions & activation route
Test still miss. Is a task for the next sprint
> [#CHK-1884] Iframes card page: errors and exceptions 

- .env.development
- src/routes/GdiCheckPage.tsx
Added a redirect to /errore route page when:
- an unknown state is received
- the Build class instance fails
Adde a redirect to /riepilogo route page when on a timeout (12000 ms default)
> [CHK-1887] Errors management on /gdi-check page route

- .devops/pagopa-deploy-pipelines.yml
- src/routes/GdiCheckPage.tsx
- src/utils/__tests__/urlUtili.test.ts
- src/utils/api/helper.ts
- src/utils/regex/urlUtilities.ts
> fix(deploy): fix eCommerce host for DEV

- src/routes/PaymentCheckPage.tsx
- src/utils/api/helper.ts
- retries added to the requestTransactionAuthorization
- else branch added to a check on sessionStorage transaction item 
- unuseful card holder label removed
retries added to manage transient network problems
> [CHK-1885]: retries added to the requestTransactionAuthorization

- package.json
- src/App.tsx
- src/features/payment/components/IframeCardForm/IframeCardForm.tsx
- src/utils/api/helper.ts
- src/utils/storage/sessionStorage.ts
Depends on pagopa/pagopa-infra/pull/1302
> [CHK-1891] Update npg interaction

- src/features/payment/components/IframeCardForm/IframeCardField.tsx
- src/features/payment/components/IframeCardForm/IframeCardForm.tsx
- Uses npg sdk error and flowChange events to set focus
- Removes the FocusProxy component to intercept focus
The focus proxy approach does not work on safari, this pr attempts to fix this issue. 
This approach causes a delay in the state update, since the events are sent on the first key press in an input.
Visual testing
> fix(iFrameCard): using npg error to set focus

- src/features/payment/components/IframeCardForm/IframeCardField.tsx
- static/npg/style.css
- Add icon adornment to indicate the input validation status
> [CHK-1914] Card data - input adornments

- .devops/azure-templates/setup-env.yml
- .devops/pagopa-deploy-pipelines.yml
- .env.development
- src/index.html
- src/npgsdk.js
- src/utils/config/config.ts
Added a new env variable (CHECKOUT_NPG_SDK_URL)
Different SDK versions are available (depending on DEV or PROD environment)
The new env variable(CHECKOUT_NPG_SDK_URL) allow to use different url per environment without changing the fe project
Changing the env variable value and building locally the FE.
> [CHK-1916] Nexi js sdk url as env variable

- .devops/pagopa-deploy-pipelines.yml
Fix e2e template path
Fix e2e template path
> fix: template path

- src/utils/api/helper.ts
- Catches and handles error in the Auth Request api call
- Shows error popup and enables submit button in case of errors
Previously errors in the Auth Request api call were not handled correctly, causing the user to be stuck on the check/payment page in case of errors, with a disabled button and no way to retry the payment call
> [CHK-1957] Auth Request error handling

- .devops/pagopa-code-review-pipelines.yml
- package.json
> Fix: added reporters for unit test into configuration

- src/utils/__tests__/validators.test.ts
- src/utils/api/helper.ts
- src/utils/regex/validators.tsx
Added a function to validate the response from the /wallets/:walletId/sessions.
When validation fails a generic error modal shows up.
With a partial or incomplete response it's useless to build the card onboarding form. It's better to give users a feedback (error modal)
Trough unit tests and a real test using the be-mock and simulating a partial response
> [CHK-2101] Validating the /wallets/:walletId/sessions response

- .devops/azure-templates/setup-env.yml
set survey_show as number instead string
- change in pipeline template from string tu number
> [BUG] set survey_show as number instead string

- .devops/azure-templates/setup-env.yml
set survey_show as number instead string
- change in pipeline template from string tu number
> [BUG] survey_show as number in pipeline

- .devops/azure-templates/setup-env.yml
- .env.development
- src/routes/GdiCheckPage.tsx
- src/routes/PaymentResponsePage.tsx
- src/utils/api/response.ts
- src/utils/config/config.ts
- src/utils/transactions/TransactionResultUtil.ts
> Feat: [CHK-2190] IO client payment response

- .devops/azure-templates/setup-env.yml
- .devops/pagopa-code-review-pipelines.yml
- .devops/pagopa-deploy-pipelines.yml
- src/utils/api/response.ts
Adds missing variables in the azure templates
> Fix:[CHK-2215] Missing template variables

- .devops/pagopa-deploy-pipelines.yml
- src/utils/__tests__/urlUtili.test.ts
Avoid ecommerce-fe purge on checkout deploy (only DEV)
> Avoid ecommerce-fe purge on deploy

- privacypolicy/it.html
- src/components/PrivacyPolicy/PrivacyInfo.tsx
- src/translations/it/translations.json
- Index page updated with a new Privacy Policy and Terms and conditions of use of the service
- PrivacyInfo Component refactor using a html tag interpolation in translation
- it translation json updated
Tested using the local FE development server
> [CHK-1892]: Privacy Policy and Terms and conditions of use of the service updated

- .devops/pagopa-deploy-pipelines.yml
Porting of end to end test execution in deploy pipeline
Porting of end to end test execution in deploy pipeline.
E2E task execution is performed using the azure pipeline template from the pagopa-checkout-tests [here](https://github.com/pagopa/pagopa-checkout-tests/blob/main/.devops/code-review-pipelines.yml)
> fix: deploy pipeline e2e test

- src/routes/PaymentResponsePage.tsx
- src/utils/__tests__/TransactionResultUtil.test.ts
- src/utils/api/response.ts
- src/utils/transactions/TransactionResultUtil.ts
- getViewOutcomeFromEcommerceResultCode function extended 
- evaluateUnauthorizedStatus function now evaluates NPG gateway and its status to calculate the final outcame
- unit tests added
The NPG integration needs new outcames to be managed
through unit tests and mocking the GET /transaction response
> [CHK-2355]: transaction-outcome mapping update

- src/components/PrivacyPolicy/PrivacyInfo.tsx
- src/components/TextFormField/PspFieldContainer.tsx
- src/components/commons/Header.tsx
- src/translations/it/translations.json
- static/privacypolicy/it.html
This PR copy 3 improvements done on "develop" branch [CHK-1892](https://github.com/pagopa/pagopa-checkout-fe/pull/299), [CHK-2225](https://github.com/pagopa/pagopa-checkout-fe/pull/301) and [CHK-2224](https://github.com/pagopa/pagopa-checkout-fe/pull/302)
Cherry pick
[CHK-1892]: https://pagopa.atlassian.net/browse/CHK-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-2225]: https://pagopa.atlassian.net/browse/CHK-2225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CHK-2224]: https://pagopa.atlassian.net/browse/CHK-2224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CHK-2491] Copy PRs of "develop" in "develop-npg"

- src/components/commons/Header.tsx
- src/components/commons/Layout.tsx
This PR try to harmonize header's padding as requested by designers.
- change padding dimensioni in layout
- change padding management in header
- cosmetic issues
> [CHK-2492]  padding tuning

- src/utils/__tests__/TransactionResultUtil.test.ts
- src/utils/api/response.ts
- src/utils/counter.ts
- src/utils/transactions/TransactionResultUtil.ts
- function getViewOutcomeFromEcommerceResultCode updated to manage new outputs according to the following internal documentation (https://pagopa.atlassian.net/wiki/spaces/I/pages/909869778/PM-NPG+-+Mapping+esito#Mapping-Esito-Pagamento-NPG)
- unit tests updated
- refactoring the polling section on GET /transaction/{idTransaction}
The previous implementation was not enough and complete
via manual test, unit tests, e2e automated tests
> [CHK-2493] transaction outcome managment with NPG gateway

- src/routes/PaymentResponsePage.tsx
Fixing a problem  with a missing import
FE doesn't build
Tested building the FE locally
> [CHK-2493] Missing import fix

- .devops/pagopa-deploy-pipelines.yml
Change `develop` to `main` branch ref into deployment pipelines
Change `develop` to `main` branch ref into deployment pipelines
> chore(pipeline): switch develop to main branch

- package.json
- src/App.tsx
- src/features/payment/components/IframeCardForm/IframeCardForm.tsx
- src/features/payment/components/PaymentChoice/PaymentChoice.tsx
- src/features/payment/components/PaymentChoice/PaymentMethod.tsx
- src/features/payment/components/PaymentChoice/utils.ts
- src/features/payment/models/paymentModel.ts
- src/routes/PaymentCheckPage.tsx
- src/routes/PaymentChoicePage.tsx
- src/routes/models/paymentMethodRoutes.tsx
- src/utils/__tests__/paymentMethodChoice.test.ts
- src/utils/api/helper.ts
- src/utils/storage/sessionStorage.ts
- yarn.lock
- Enable navigation from method choice to other routes
- Transaction request is made if payment method choice
differs from CP code type
- Check page method edit navigate back to method choice
if method type differs from CP
- Adds a loader on method choice transaction
- Payment method information is passed between routes
using a sessionStorage object
- api service name is used for check page method title
- api service description is used for check page method body
Enables the possibility of using any future payment method type returned from the api service. 
This pr does not concern itself with UI/UX apart from a temporary loader shown during the transaction resulting in choosing a payment method type code that differs from  `CP` (credicard)
> Feat: [CHK-2551] Apm methods routing

- src/utils/api/helper.ts
Fixes an error in the object naming while saving the payment method info, causing the leastFourDigits to not be shown in the CheckPage
> Fix: [CHK-2604] CheckPage card lastFourDigits fix

- package.json
- src/features/payment/components/PaymentChoice/PaymentChoice.tsx
- src/features/payment/models/paymentModel.ts
- src/routes/PaymentCheckPage.tsx
- src/routes/models/paymentMethodRoutes.tsx
- src/utils/api/helper.ts
- yarn.lock
- CheckPage card edit navigates to payment choice
regardless of the selected method code type
- Provides mock values for the transaction api
on apm payment methods selection
> Fix: [CHK-2605] [CHK-2606] Card edit navigation & mock apm transaction data

- package.json
- src/features/payment/components/PaymentPspDrawer/PaymentPspDrawer.tsx
- src/routes/PaymentCheckPage.tsx
use pspBusinessName in place of bundle name
> [CHK-2591] use pspBusinessName in place of bundle name

- src/features/payment/components/PaymentChoice/PaymentChoice.tsx
- src/features/payment/components/PaymentChoice/PaymentMethod.tsx
- src/features/payment/components/PaymentChoice/PaymentMethodImage.tsx
- src/features/payment/models/paymentModel.ts
- src/routes/PaymentCheckPage.tsx
This PR add logos to the paymethods list
- manage asset from BE service
> [#CHK-2548]  add logos to paymethods list

- src/routes/PaymentCheckPage.tsx
- src/utils/api/helper.ts
- Change authorization request for redirect payment flow.
- Handle authorization url redirect to external domains (redirect payment flow)
Those modifications are needed in order to properly handle redirect payment flow
Local tests + test in dev environment
> fix: redirect auth request body

- src/features/payment/components/IframeCardForm/IframeCardField.tsx
- src/index.html
This PR try to enhance the reactiveness of InputCardPage
- add Nexigroup.com subdomains in prefetch at the load of the webapp
- drop setTimeout to serve immediately fields when the `src` is not empty
> [#CHK-2635] Reactiveness enhancement for InputCardPage with npg

- .devops/azure-templates/setup-env.yml
- .devops/pagopa-deploy-pipelines.yml
- src/utils/api/helper.ts
* add support for invoking authorization request for PayPal
* add support for invoking authorization request for BancomatPay
* add support for invoking authorization request for MyBank
* Populate `window._env_.CHECKOUT_VERSION` with branch name and commit SHA of deployed version
Needed to pay with PayPal/BancomatPay/MyBank
> [CHK-2703] feat(apm): add support for invoking authorization request for APMs

- .devops/pagopa-deploy-pipelines.yml
Update deploy pipeline to avoid ecommerce-fe removal
> [CHK-2746] exclude ecommerce-fe dir from sync

- .devops/pagopa-deploy-pipelines.yml
exclude ecommerce-fe from cdn sync storage in deploy step
> fix(deploy): exclude ecommerce-fe from cdn sync storage

- src/routes/PaymentSummaryPage.tsx
- src/utils/api/client.ts
- src/utils/api/helper.ts
Handling error in PaymentCheck submit
- Handle max-retries error to show error popup
- eCommerce client doesn't perform retries if `auth-request` returns 4xx code
Improve user experience in checkout
> [CHK-2626] Add onError handling in auth request page

- src/features/payment/components/IframeCardForm/IframeCardField.tsx
- src/features/payment/components/IframeCardForm/IframeCardForm.tsx
- src/utils/buildConfig.ts
- use allFiledsLoaded NPG callback
The goal of this PR is to use the new NPG `allFiledsLoaded` feature to show input text only after all iframes have been fully loaded.
> feat(iframe): use allFiledsLoaded npg sdk

- .devops/pagopa-deploy-pipelines.yml
Increase UAT timeout
Increase UAT timeout
> fix: increate checkout timeout

- src/components/PageContent/CheckoutLoader.tsx
> [#CHK-2830] drop unuseful border

- src/components/PageContent/CheckoutLoader.tsx
- src/components/commons/Header.tsx
This PR refact the overlay div to show spinner when loading
> [#CHK-2830] refact overlay

- src/index.html
Changed HTML meta descriptions to now include more payment methods supported by Checkout
> [CHK-3033] Changed meta descriptions

- src/features/payment/components/PaymentChoice/PaymentChoice.tsx
- src/routes/IframeCardPage.tsx
Show popup error when error occurs during activation for apm payments
> [CHK-3113] fix: show popup on apm activation error

- src/utils/api/helper.ts
Add handling for iConto RICO redirect payment type code
Add handling for iConto RICO redirect payment type code
Test in DEV environment
> Chk 3027 add i conto redirect

- src/components/modals/ErrorModal.tsx
- src/routes/PaymentNoticePage.tsx
Add ids to ErrorModal component to identify them via selector in the tests suite
> [CHK-3204] add error modal ids

- src/translations/de/translations.json
- src/translations/en/translations.json
- src/translations/fr/translations.json
- src/translations/it/translations.json
- src/translations/sl/translations.json
This PR fixes some wrong translations in the cart detail drawer
> Copy fixes

- package.json
Update package json version to be aligned with release. It's set to bigger release version, so we will release a major version (4.0.0) to be aligned with the bigger version so far.
> [CHK-3206] set version to align release branch

- .devops/pagopa-deploy-pipelines.yml
-  increase gdi check timeout
The goal of this PR is to increase gdi-check step timeout before polling for the transaction outcome  begins.
> fix: increase gdi-check timeout

- src/routes/KOPage.tsx
Fix close button label
Fix close button label
local test opening /errore page
Broken page
Fixed
> fix: close button label

- src/routes/PaymentResponsePage.tsx
- src/routes/PaymentResponsePageV2.tsx
- src/utils/storage/sessionStorage.ts
Cart return url is now a react state, making it persistent to state updates
Solves data being lost on page update
Manual testing
new behavior is correct
> Bugfix [CHK-3630] Cart return url made persistent using react state

- src/routes/PaymentSummaryPage.tsx
Replaced info icon with iconButton
Manual testing
> [CHK-3396] Replaced info icon with iconButton

- src/components/TextFormField/PspFieldContainer.tsx
Fixed invalid role, removed attribute
> [CHK-3481] Fix invalid role, removed

- src/features/payment/components/PaymentPspDrawer/PaymentPspDrawer.tsx
Added programmatic handling of the component outline in case of focus gain/loss through tab navigation. Added a filter that excludes the outline for focus acquired in case of mouse click.
> [CHK-3482] Fix hidden elements getting focus

- src/routes/PaymentCheckPage.tsx
Removed pspEditLoading from the set of booleans variables used to disable all buttons on the page
> [CHK-3484] Fix lost focus when closing PSP drawer

- src/components/TextFormField/PspFieldContainer.tsx
Fixed drawer closing and reopening after enter key press
Bugfix
Manual testing
> [CHK-3667] Fixed drawer closing and reopening after enter key press

- .devops/azure-templates/setup-env.yml
Change GDI check timeout default value to 20 sec to align this value to the one used in all envs
Change GDI check timeout default value to 20 sec to align this value to the one used in all envs
> fix: change GDI timeout default value

- src/components/commons/Footer.tsx
Updated accessibility link to https://form.agid.gov.it/view/db845560-df2d-11ef-8637-9f856ac3da10
> [CHK-3675] Updated accessibility link

- src/components/commons/Header.tsx
- src/utils/api/helper.ts
Updated signature and usage of feature flag api to match new batch format
manually
> [CHK-3714] Updated feature flag API signature

- .proxyrc.js
- src/App.tsx
- src/components/commons/Footer.tsx
- src/components/commons/Header.tsx
- src/components/commons/LoginHeader.tsx
- src/translations/it/translations.json
- src/utils/api/helper.ts
- src/utils/storage/sessionStorage.ts
- add new top header with "login" button
- after clicking "login" a sample user is saved on session storage and on react state
- "login" button is visible until choose payment method page
- "logout" can be done until the end of the payment flow
- when payment flow ends, logged user is removed from session storage like other session data
The goal of this PR is to add header that contain login button with basic authentication flow. For this PR login action is mocked with hardcoded user sample.
Login
Logged user
Logout
> [CHK-3715] feat: add login header until choose payment method page

- .devops/pagopa-code-review-pipelines.yml
- jest.config.js
- package.json
- src/routes/AuthCallbackPage.tsx
- src/routes/__tests__/AuthCallbackPage.test.tsx
- yarn.lock
Retry button now repeats whole login
Refined requirements pointed in this direction
Manual test
> [CHK-3768] Retry button now repeats login

- jest-puppeteer.config.js
- src/__integration_tests__/authentication.integration.test.ts
- src/routes/AuthCallbackPage.tsx
Updated Integration tests to validate the new behavior of the "retry" button
This is part of a bigger effort to improve sicurity
Integration tests, jest
> [CHK-3769] Add/Update integration tests on auth-callback page

- src/__integration_tests__/paymentflow.integration.test.ts
- Added a new integration test to `paymentflow.integration.test.ts`:
- Covers form submission with valid data.
- Checks presence of PSP selection screen.
- Selects a PSP and verifies redirection to the payment summary.
We need to ensure the full checkout flow, including PSP selection, works as expected in an integration environment.
> feat: [CHK-3869] integration tests psp list

- .devops/pagopa-code-review-pipelines.yml
Add test coverage to code by codecov review pipeline
> [CHK-3982] add test coverage script

- .devops/pagopa-code-review-pipelines.yml
This reverts commit f12ba3843e0d6ebbaa60d9b4450d3e7ba9f192dc.
> [CHK-3982] Revert codecov

- src/__integration_tests__/authentication.integration.test.ts
- src/__integration_tests__/paymentflow.integration.test.ts
- src/__integration_tests__/utils/helpers.js
Fixed the following integration tests:
- Checkout Payment - PSP Selection Flow
-     ✕ Should fill form, select PSP, and proceed with payment (IT)
-     ✕ Should mock PSP list with one PSP and proceed with selection
> [PIDM-416] fix(test) fix integration tests

- src/components/PrivacyPolicy/PrivacyInfo.tsx
- src/components/commons/Footer.tsx
Updated footer and privacy info components href to point to cdn
> [PIDM-307] feat(tos): update hrefs

- sonar-project.properties
Update sonar-project.properties
> [CHK-4034] Fix sonar config to exclude test files 

- src/utils/api/helpers/ecommerce/ecommerceTransactionsHelper.ts
Add handling for Google Pay APM NPG payment method (type code GOOG)
Add handling for Google Pay APM NPG payment method (type code GOOG)
> feat: add handling for Google pay payment method

- .devops/pagopa-deploy-pipelines.yml
> chore(pipeline): update vm agent version

- src/features/payment/models/paymentModel.ts
- src/routes/models/paymentMethodRoutes.tsx
- src/utils/api/helpers/ecommerce/ecommerceTransactionsHelper.ts
Add klarna payment type code to show it in payment method list
> PIDM-710: add Klarna payment method type code

- .devops/pagopa-code-review-pipelines.yml
- package.json
- src/__integration_tests__/outcomes.integration.test.ts
- src/__integration_tests__/paymentflow.integration.test.ts
- src/__integration_tests__/utils/helpers.js
- src/routes/KOPage.tsx
- src/routes/__tests__/IndexPage.test.tsx
- src/routes/__tests__/PaymentEmailPage.test.tsx
- src/utils/__tests__/storage/sessionStorage.test.ts
- yarn.lock
> chore: integration test fix

- src/components/modals/ErrorModal.tsx
- fixed the wrong event send for FaultCategoryEnum.GENERIC_ERROR
> fix: [PIDM-772] mixpanel error modal event

- src/routes/PaymentResponsePageV2.tsx
Remove padding for survey link box
Porting of the fix done [here](https://github.com/pagopa/pagopa-checkout-fe/pull/559) also for PaymentResponsePageV2
local test
> chore: remove padding from survey box

- src/__integration_tests__/paymentflow.integration.test.ts
- src/__integration_tests__/utils/helpers.js
- src/components/TextFormField/TextFormField.tsx
- src/features/payment/components/PaymentChoice/PaymentChoice.tsx
- src/features/payment/components/PaymentChoice/__tests__/PaymentChoice.test.tsx
- src/routes/__tests__/PaymentChoicePage.test.tsx
- src/translations/de/translations.json
- src/translations/en/translations.json
- src/translations/fr/translations.json
- src/translations/it/translations.json
- src/translations/sl/translations.json
Introduce payment method list filter box in payment methods page
In the payment method page add a searchbox to filter all payment methods shown in the list by their names
Introducing a new feature for payment method page
Test executed:
- in local env
- unit tests 
- integration tests
> (feat) CHK-4332: add filter box in payment method page

- src/__integration_tests__/paymentflow.integration.test.ts
- src/__integration_tests__/utils/helpers.js
- src/features/payment/components/PaymentChoice/PaymentChoice.tsx
- src/translations/de/translations.json
- src/translations/en/translations.json
- src/translations/fr/translations.json
- src/translations/it/translations.json
- src/translations/sl/translations.json
Minor fixes for payment choice page
Update for:
- translations
- empty method filter message
- margin and size 
No clear button if no filter is set
<br/>
<br/>
Clear button visible if filter keyword is set
<br/>
<br/>
Empty method messages with updated margin and font-size
> feat: [CHK-4432] update translations
