pagopa/pagopa-checkout-fe

package.json, src/utils/api/helper.ts
- use detail instead detail_v2 in payment activations error
The goal of this PR is to restore the `detail` instead of `detail_v2` waintg for https://pagopa.atlassian.net/browse/IOPAY-594
=> Fix detail instead detail_v2

.devops/pagopa-deploy-pipelines.yml
- move manual prod approval after prod build
The goal of this PR is to reduce the time between approval and actual deployment by moving the build step to prod first.
Check next deploy in prod :-)
- [] I have updated the documentation accordingly.
=> [CHK-323] Manual prod approval after prod build

src/components/commons/Header.tsx
This PR make "tappable" the whole div on header (when in mobile breakpoint)
- slice the event on the parent div instead the "info" image
- Better UX
=> [#CHK-43] Tap the whole div to show amount on mobile

src/components/Header/DrawerDetail.tsx, src/components/TextFormField/FieldContainer.tsx, src/components/commons/Header.tsx
This PR fixes long payment info text not wrapping accordingly in the header, header drawer and payment summary page, causing bad view on mobile/small devices. 
Fix long payment info text
Added "/dona" as ignored path for header view
=> Fix long payment detail text

src/routes/DonationPage.tsx
With a new version, the App (on iOS) will not support a "donation". So, it's necessary to drop off the relative button's.
- Added style to hide the button on mobile viewport
Read above
=> [#CHK-469] Disable "dona con io" on mobile

src/utils/api/helper.ts
This PR drop fiscalCode to start-session call
- Putting an empty string to helper when call startSessionUsingPOST
- In admin-panel we've not to list fiscal-code of user
=> [#CHK-719] Drop fiscalCode from POST to start-session

src/routes/PaymentResponsePage.tsx, src/routes/PaymentSummaryPage.tsx, src/utils/api/apiService.ts, src/utils/api/helper.ts
When a payment flow returns KO, we have to expose the correct url to the "close button"
- Fix manage of KOurl considering idStatus
- fix payportal origin dropping unusefful condition
- fix cf name in summary
=> [#CHK-833] Return url in case of KO

src/routes/PaymentCheckPage.tsx
This PR set on "0" the amount limit to show disclaimer at the bottom of PSP's commission  
- Set 0 on `disclaimerUpperLimit` 
Silent mode, for now
=> [#CHK-994] amount limit to show disclaimer set on 0

src/utils/__tests__/TransactionResultUtil.test.ts, src/utils/transactions/TransactionResultUtil.ts
Managed three new states to stop polling on the get transaction for the outcome page
Three new transaction states have been managed that allow polling  stop. 
1. AUTHORIZATION_FAILED
2. CLOSURE_FAILED 
3. NOTIFIED_FAILED
AUTHORIZATION_FAILED status ends the authorization denied page
The tests were performed locally
=> Fix polling trasaction status

src/features/payment/models/paymentModel.ts, src/routes/CancelledPage.tsx, src/routes/IndexPage.tsx, src/routes/KOPage.tsx, src/routes/PaymentCartPage.tsx, src/routes/PaymentResponsePage.tsx, src/utils/storage/sessionStorage.ts
Use sessionStorage objects only when strictly necessary...
- definition of returnUrls' Interface without export, cause we use Cart instead
- drop returnUrls interface from all the files occurred
- refactoring of returnUrls with Cart.returnUrls when needed
- drop of ClearSensitiveItems and creation of ClearStorage (useful to reset sessionStorage dataset)
We don't need a specific key in sessionStorage to store returnUrls cause when a flow is started from the first page of Checkout every finally CTA (success, ko, cancel, etc) must redirect user to the home. When the flow starts with a Cart we can catch the urls from a subset of info called "returnUrls".
- Manual
- Linter
- E2e
=> [#CHK-1111] Drop returnUrls from SessionStorage

package.json, src/features/payment/models/paymentModel.ts, src/routes/InputCardPage.tsx, src/routes/PaymentCheckPage.tsx, src/routes/PaymentChoicePage.tsx, src/routes/PaymentResponsePage.tsx, src/utils/api/helper.ts, src/utils/api/response.ts, src/utils/storage/sessionStorage.ts
This pr use new calculateFee api from ecommerce to get psp list
Change api invocation for psp list
Remove PspSelected, PspList and Transaction data structure from PaymentModel. Use in place of the autogenerated data structure from openapi.
Update activate/getPsp(calucateFee) flow.
Tune checkout to the new api exposed from payment-methods that now asks for psp list from gec. Since new data structures are involved the old ones has been deleted
Test were performed locally. Integration test fails in pipeline since the mock branch has to be merged (https://github.com/pagopa/pagopa-checkout-be-mock/pull/33). Integration tests performed locally are successfully
=> [CHK-1188] add new openapi reference and update model

src/features/payment/components/PaymentNoticeForm/PaymentNoticeForm.tsx
Same as #241 but based on develop branch
Enforce the input regex to valid insert payment notice number page form
Upgrade regex input to check if the input string for the rpt id is a string of exactly 18 digits for payment notice number and 11 digits for pa fiscal code
This PR addresses a log evidence about the fact that eCommerce receives some dirty inputs from checkout frontend.
Old regex `\d{18}` and `\d{11}` for notice number and pa fiscal code validated respectively input as `302000100000009424-` and `77777777777-` (note the ending dash)
=> fix(checkout) CHK-1761 enforce rptid regex

src/components/commons/SurveyLink.tsx, src/routes/PaymentResponsePage.tsx, src/translations/it/translations.ts, src/utils/config/mixpanelDefs.ts
Added an info alert component which includes a link to a Qualtrics survey on the thank you page (alert visible only when the payment is ok)
The purpose is to measure the ease of the payment process experience
Tested locally using the be-mock as backend and simulating an ok and ko payment
=> [CHK-1690] Qualtrics survey on thank you page

package.json, src/features/payment/components/IframeCardForm/IframeCardForm.tsx, src/routes/IframeCardPage.tsx, src/routes/InputCardPage.tsx, src/routes/PaymentCheckPage.tsx, src/utils/api/helper.ts, src/utils/storage/sessionStorage.ts
Add the frontend logic to invoke payment method sessions when npg is ready for payment
- add invoke function when npg is in ready_to_payment state
- add invoke to npg session api via payment-methods bewtween post transaction and calculate fees
- adapt frontend to new data structure
=> [Chk-1822] feat(sessions): invoke payment sessions method to retrieve card data

src/features/payment/components/PaymentChoice/PaymentChoice.tsx, src/routes/PaymentCheckPage.tsx
- payment choice page uses location assign to navigate to card data page 
- payment check page removes `beforeunload` listener before navigating back to card data page
- payment check page uses location replace to navigate back to card data page 
Use location replace or assign instead of router-dom navigate so to
cause a window reload and cleaning the window from frames
loaded by previous npg sdk builds
Visual testing
=> [CHK-1826] fix card form duplication

src/features/payment/components/IframeCardForm/IframeCardField.tsx, src/features/payment/components/IframeCardForm/IframeCardForm.tsx, src/features/payment/components/IframeCardForm/types.ts
This commit tries to reproduce the border ux of @mui `TextField` component.
- Structured styling for the `RenderField` component
- Extracted border styles calculation
- Extracted typing to types file
Using the embedded npg payment frames prevents the use of the TextField mui component used in forms of other payment pages.
Visual testing
=> [CHK-1818] mui ux IframeCardField and refactor

src/features/payment/components/IframeCardForm/IframeCardField.tsx, src/features/payment/components/IframeCardForm/IframeCardForm.tsx, src/utils/buildConfig.ts, static/normalize.css, static/npg/style.css
- Material ui skeleton showed for 2s before displaying the card data form
- Improved style and npg css to extend the input area to the full box wrapper size
- Fixed adornment aria role attribute
This pr tries to reduce the flash of unstyled content while the npg iframes are loading the css.
Since is not possible to know exactly when the iframes are fully loaded, a 2s timeout is used.
- Visual testing
- Linux screen reader (a11y)
- Axe dev-tools (a11y)
=> [CHK-1912] iFrameCardForm Skeleton

src/features/payment/components/IframeCardForm/IframeCardField.tsx, src/features/payment/components/IframeCardForm/IframeCardForm.tsx
I have simply removed the iframe field during the loading phase giving to the skeleton the right dimensions
Just one instance of every iframe field is needed to trigger Nexi sdk events correctly
Tested locally using the BE mock as back-end service
=> [CHK-1943] Card data form bug: removing duplicated iframe fields during skeleton loading phase

src/features/payment/components/IframeCardForm/IframeCardForm.tsx, src/routes/IframeCardPage.tsx, src/utils/api/helper.ts
This PR adds recaptcha check to the "sessions" and "transactions" calls.
Depends on [this PR](https://github.com/pagopa/pagopa-checkout-be-mock/pull/63)
- added recaptcha
- refact recaptcha init
=> [#CHK-1895]  add recaptcha to sessions transactions

src/routes/PaymentCheckPage.tsx
When a user refresh the check payment page, we've to redirect him to the previous page instead show an error (caused by the missing of threshold value stored in redux)
- put a redirect in the miss `if` 
Solve the bug
=> [CHK-2142] Redirect instead reload when miss Threshold

src/features/payment/components/IframeCardForm/IframeCardForm.tsx
This PR intends to fix the problem when a user go back from the check-page. 
- even if there is a "transactionID" we start a new transaction overriding the previous one
- drop the if & function of retrieve
Solve the bug
=> [CHK-2139] bug edit and back

src/features/payment/components/IframeCardForm/IframeCardField.tsx
This PR try to solve the bug listed using a `location.replace` directive instead of the use of "src attribute".
Firefox only at the pressure of the back button try "to back" the iframe instead the main page.
- write a function to populate the form source via _location_
Solve the bug
- visual/manual testing
=> [CHK-2138] Back button bug's

src/routes/PaymentCheckPage.tsx
This PR fixes the bug #CHK-2214 setting "false" the show of the disclaimer in the checkpage qhen the method is not "on us"
- set false when not on us
=> [#CHK-2214] Set false if card is not on us

src/components/TextFormField/PspFieldContainer.tsx
This fix try to harmonize the PSPs list with a max height of logos
- add max height to imgs
Fix the bug 2225
=> [CHK-2225] Psps logo height

src/features/payment/components/PaymentChoice/PaymentChoice.tsx, src/features/payment/components/PaymentChoice/PaymentMethod.tsx
The bug occur when a user try to select a payment method obtaining an errore instead a redirect to a page.
- Print the description value instead the name
- import the correct utility to track the selection of a method
Solve the bug
=> [#CHK-2594] Click on a payment method

src/features/payment/components/IframeCardForm/IframeCardField.tsx
This PR solve a problem on Firefox browser.
- drop lazy attribute from `iframe`
=> [CHK-2611] Drop laxyloading attribute from npg iframe

src/features/payment/components/PaymentChoice/PaymentMethod.tsx
Use card generic png icon also payment method card in place of svg icon
Remove svg icon present only for payment method card item in payment method choice page
=> [CHK-2622] use card remote icon

.devops/pagopa-code-review-pipelines.yml, src/routes/PaymentChoicePage.tsx
The loop between select method page and insert email page when pressing back button is caused by pushing another email page on history stack. The email page use `navigate(-1)` on back press and the previously page is select method when coming from it, so this generate a loop. To solve it, just pop from history stack the select method page to go back to email page.
=> fix: [CHK-2640] Back loop between select method and insert email

src/routes/PaymentCheckPage.tsx, src/utils/api/helper.ts
This PR fix the following issue: after pressing "Pay" the button become unclickable and thats ok. Cause the flag `PayLoading` is set to false before start redirect, the button become clickable, while redirection is loading. This is especially visibile when redirection loading is slow.
I also attempted to use the "beforeunload" event, but it is fired before the redirection is completed and produces the same effect as the bug.
- when a payment requires a redirection the flag will not be set to false
- add missing await on async functions
=> [CHK-2745] Stop payment in progress loading after redirect

.devops/pagopa-deploy-pipelines.yml
Fix deploy-pipeline
The double `exclude-path` option for sync command exclude the first one and undesired delete happens
=> [CHK-2851] fix exclude path double path

src/components/TextFormField/PspFieldContainer.tsx
This PR fix a problem with psp logos with a 16:9 ratio
- added a container for the img tag
Solve the bug
=> Better manage of psp logo's ratio

src/index.html
- add meta tag to disable  cache only for index.html
The goal of the PR is to disable any caching on the `index.html` page, which is causing 404 errors due to outdated JS references. This fix is necessary to resolve issues of 'blank pages.' In addition to this fix, we will also intervene on the CDN to perform a purge on the individual resource.
=> fix: CHK-3174 disable cache only for index.html

src/components/Header/DrawerCart.tsx
The goal of this PR is to Do not display the "Notice Code" field in the Cart section on the first two pages:
- `/inserisci-email`
- `/scegli-metodo`
-  `/inserisci-carta`
ONLY for WISP_REDIRECT flow.
Before:
Now:
=> fix(WISP_REDIRECT): CHK-3495 payment notice only for subset page wisp redirect

src/components/TextFormField/ClickableFieldContainer.tsx
props.clickable now determs if whe initialize an onClick and onKeyDown handler, removing the handlers when not needed
=> [CHK-3478] Focusable text should not allow clicks

src/__integration_tests__/paymentflow.integration.test.ts, src/components/commons/LoginHeader.tsx, src/features/payment/components/IframeCardForm/IframeCardForm.tsx, src/features/payment/components/PaymentChoice/PaymentChoice.tsx, src/routes/CancelledPage.tsx, src/routes/InputCardPage.tsx, src/routes/KOPage.tsx, src/routes/PaymentCheckPage.tsx, src/routes/PaymentResponsePage.tsx, src/routes/PaymentResponsePageV2.tsx, src/routes/SessionExpiredPage.tsx
- if `authToken `on `sessionStorage `is not present, discard get user response of LoginHeader (both success and error case)
- change `window.location.replace` with `navigate` in order to prevent app to be refreshed on redirect to internal page
The goal of this PR is to fix a racing condition of **get users** with **logout** after a payment error.
On error page a get user is performed despite having previously logged out.
On error page logged user must not be present
Before 
After
=> [CHK-3806] fix: get user info after logout 

src/routes/PaymentResponsePage.tsx
Padding on extra small devices has been removed due to not being the desired final product.
Manual testing in local environment.
=> fix: [PIDM-708] removed unwanted padding on banner
